name = "osintag"
main = "worker.js"
compatibility_date = "2024-03-22"

[[kv_namespaces]]
binding = "OSINTAG_KV"
id = "adaa9aec60c94e06b05473b8837a004b"

[[queues.producers]]
queue = "osint-queue"
binding = "OSINT_QUEUE"

[[queues.consumers]]
queue = "osint-queue"  # אותו תור בדיוק
# בלי script_name בכלל כי אותו worker מאזין ומטפל

[observability.logs]
enabled = true

[env.production]
kv_namespaces = [{ binding = "OSINTAG_KV", id = "adaa9aec60c94e06b05473b8837a004b" }]
