name = "osintag"
main = "worker.js"
compatibility_date = "2024-03-22"

[[d1_databases]]
binding = "DB"
database_id = "3ab661e4-345d-47d6-8214-64dc2d5a7282"
database_name = "osintag"

[[queues.producers]]
queue = "osint-queue"
binding = "OSINT_QUEUE"

[[queues.consumers]]
queue = "osint-queue"  # אותו תור בדיוק
# בלי script_name בכלל כי אותו worker מאזין ומטפל

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

invocation_logs = false

[env.production]
kv_namespaces = [{ binding = "OSINTAG_KV", id = "adaa9aec60c94e06b05473b8837a004b" }]

